apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: react-frontend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10